name: Android CI for Sunflower

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK for Android
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Set up Gradle cache for faster builds
      - name: Set up Gradle Cache
        uses: gradle/gradle-build-action@v2

      # Step 4: Grant Gradle Wrapper executable permission
      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      # Step 5: Build the Android app
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 6: Run unit tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Step 7: Upload Debug APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Step 8: Run Lint checks (Optional)
      - name: Run Lint Checks
        run: ./gradlew lint
